- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ec2-user
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      set -eux

      git checkout .

      docker build -t docker1 .
      docker run -p 8078:8080 -d --name swathi docker1

      docker ps -a
      docker logs docker1 || true
