name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -eux

            cd /home/ec2-user/project-name  # go to the project directory
            git pull origin main            # pull the latest code

            docker stop swathi123 || true
            docker rm swathi123 || true

            docker build -t docker1 .
            docker run -p 8082:8080 -d --name swathi123 docker1

            docker ps -a
            docker logs swathi123 || true
